//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RailDiag.rc
//
#define IDR_RAILSPLIT                   5
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_RAILDITYPE                  129
#define IDD_DLG_STATE                   130
#define IDB_MTU                         131
#define IDD_COM_SETTINGS                132
#define IDD_MODEM_SETTINGS              133
#define IDD_LOC_SETTINGS                135
#define IDD_PROGRESS                    136
#define IDB_MTU_TITLE_BOLD              139
#define IDB_MTU_MONO                    141
#define IDD_PHONE_BOOK                  142
#define IDD_PHONE_BOOK_ENTRY            143
#define IDB_PHONE_BOOK                  144
#define IDI_CONNECT                     145
#define IDI_DISCONNECT                  146
#define IDD_MODEM_SETTINGS2             147
#define IDR_TOOLBAR2                    148
#define IDD_PROGRESS_FLEET              148
#define IDD_FLEET_EDIT                  149
#define IDD_FLEET_NEW                   152
#define IDD_FLEET_SEL                   153
#define IDR_FLEET                       155
#define IDR_TOOLBAR3                    156
#define IDC_ST_COMPANY                  1000
#define IDC_ST_LOCTYPE                  1001
#define IDC_ST_LOC_TYPE                 1001
#define IDC_ST_LOCNR                    1002
#define IDC_ST_LOC_NUMBER               1002
#define IDC_ST_MOTORTYPE                1003
#define IDC_ST_MOTOR_TYPE               1003
#define IDC_ST_MOTORNR                  1004
#define IDC_ST_MOTOR_NUMBER             1004
#define IDC_ST_TERM_DATE                1005
#define IDC_ST_TERM_DATETIME            1005
#define IDC_ST_MTU_ORDER_NUMBER         1005
#define IDC_ST_DIAG_DATE                1006
#define IDC_ST_DIAG_DATETIME            1006
#define IDC_ST_PIN                      1006
#define IDC_ST_TERM_TIME                1007
#define IDC_ST_MESSAGE                  1007
#define IDC_ST_DIAG_TIME                1008
#define IDC_ST_PUK                      1008
#define IDC_ST_MTU_1                    1009
#define IDC_ST_DISPLAY_TEL_NUM          1009
#define IDC_ED_COMPANY                  1010
#define IDC_ED_LOCTYPE                  1011
#define IDC_ED_LOC_NUMBER               1011
#define IDC_ED_LOCNR                    1012
#define IDC_COM_PORT                    1012
#define IDC_ED_MOTOR_TYPE               1012
#define IDC_ED_MOTORTYPE                1013
#define IDC_COM_BPS                     1013
#define IDC_ED_MOTOR_NUMBER             1013
#define IDC_ED_MOTORNR                  1014
#define IDC_COM_BITS                    1014
#define IDC_ED_MTU_ORDER_NUMBER         1014
#define IDC_COM_PARITY                  1015
#define IDC_ED_CONN_NUMBER              1015
#define IDC_ED_LOC_TYPE                 1015
#define IDC_ST_DURCOUNT                 1016
#define IDC_COM_STOP_BITS               1016
#define IDC_ED_CONN_PIN                 1016
#define IDC_ED_PIN                      1016
#define IDC_ST_MODE                     1017
#define IDC_COM_CONTROL                 1017
#define IDC_CM_CONN_NAME                1017
#define IDC_ED_PUK                      1017
#define IDC_ED_TERM_DATE                1018
#define IDC_ED_TERM_DATETIME            1018
#define IDC_ED_CONN_DESC                1018
#define IDC_ED_DISPLAY_TEL_NUM          1018
#define IDC_ED_DIAL_PREFIX              1018
#define IDC_ED_DIAG_DATE                1019
#define IDC_ED_DIAG_DATETIME            1019
#define IDC_ED_CONN_PUK                 1019
#define IDC_ED_INHIBIT_TIME             1019
#define IDC_DIAL_PREFIX_VIEW            1019
#define IDC_ED_DURCOUNT                 1020
#define IDC_ST_INHIBIT_TIME             1020
#define IDC_ED_TERM_TIME                1021
#define IDC_ST_MTU1                     1021
#define IDC_ED_TEL_NUM_SMS1             1021
#define IDC_ED_DIAG_TIME                1022
#define IDC_ST_MTU2                     1022
#define IDC_ST_TEL_NUM_SMS1             1022
#define IDC_ED_MODE                     1023
#define IDC_COPYRIGHT                   1023
#define IDC_ED_TEL_NUM_SMS2             1023
#define IDC_VERSION                     1024
#define IDC_ST_TEL_NUM_SMS2             1024
#define IDC_DESCRIPTION                 1025
#define IDC_ED_TEL_NUM_SMS3             1025
#define IDC_COMB_EX_LANG                1026
#define IDC_ST_TEL_NUM_SMS3             1026
#define IDC_ST_INHIBIT_TIME2            1027
#define IDC_PROG_PROGRESS               1028
#define IDC_ST_PROGRESS                 1029
#define IDC_PROG_FLEET                  1030
#define IDC_ST_COM_PORT                 1031
#define IDC_ST_PROGR_FLEET              1031
#define IDC_ST_PROGRESS_FLEET           1031
#define IDC_ST_COM_BPS                  1032
#define IDC_ST_COM_BITS                 1033
#define IDC_ST_COM_PARITY               1034
#define IDC_ST_COM_STOP_BITS            1035
#define IDC_ST_COM_CONTROL              1036
#define IDC_ST_CONN_NAME                1037
#define IDC_ST_CONN_NUMBER              1038
#define IDC_ST_HELP_DIAL_PREFIX         1038
#define IDC_ST_CONN_PIN                 1039
#define IDC_SETTINGS_SEND               1040
#define IDC_ST_CONN_DESC                1040
#define IDC_SAVE_PIN                    1041
#define IDC_SETTINGS_LOAD               1041
#define IDC_ST_CONN_PUK                 1042
#define IDC_SETTINGS_SAVE               1042
#define IDC_DELETE_ENTRY                1044
#define IDC_DIAL_PREFIX                 1044
#define IDC_NEW_ENTRY                   1045
#define IDC_EDIT_ENTRY                  1046
#define IDC_LIST_PHONE                  1047
#define IDC_DESC_ED                     1048
#define IDC_PHB_EXPORT                  1048
#define IDC_NUMBER_ED                   1049
#define IDC_PHB_IMPORT                  1049
#define IDC_DESC_ST                     1050
#define IDC_NUMBER_ST                   1051
#define IDC_ST_HELP_NUMBER              1052
#define IDC_CONN_PHONE_BOOK             1053
#define IDC_SETTINGS                    1054
#define IDC_PHONELIST_FLEET             1056
#define IDC_SET_LOK                     1057
#define IDC_RESET_LOK                   1058
#define IDC_LIST_FLEET                  1059
#define IDC_FLEET_NAME                  1060
#define ID_NEW                          1061
#define ID_DEL                          1062
#define ID_SAVE                         1063
#define ID_FLEET_IMPORT                 1063
#define ID_FLEET_EXPORT                 1064
#define IDC_ST_FLEET_PHONE_BOOK         1065
#define IDC_ST_FLEET                    1066
#define IDC_COMB_EX_FLEET               1066
#define ID_COM_CONNECT                  32773
#define ID_COM_DISCONNECT               32775
#define ID_COM_SETTINGS                 32776
#define ID_CONN_TYPE_SERIAL             32777
#define ID_CONN_TYPE_MODEM              32778
#define ID_CONN_STATE                   32779
#define ID_CONN_LEVEL                   32780
#define ID_NEW_BIN_DATA                 32781
#define ID_NEW_ANA_DATA                 32782
#define ID_NEW_ALARM_DATA               32783
#define ID_NEW_HIST_DATA                32784
#define ID_LOC_SETTINGS                 32785
#define ID_LOC_SETTINGS_SEND            32786
#define ID_NEW_HIST20_DATA              32794
#define ID_NEW_HIST100_DATA             32795
#define ID_FILE_EXPORT                  32796
#define ID_RELOAD_DATA                  32800
#define ID_CONN_ERROR                   32801
#define ID_PHONE_BOOK                   32803
#define ID_COM_DISCONNECT_SER           32807
#define ID_COM_DISCONNECT_MODEM         32808
#define ID_NEW_DURATION_DATA            32809
#define ID_COM_STATE                    32810
#define ID_NEW_HIST2_DATA               32815
#define ID_FLEET_MGR                    32816
#define ID_FLEET_EDIT                   32818
#define ID_BUTTON32822                  32822

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        158
#define _APS_NEXT_COMMAND_VALUE         32823
#define _APS_NEXT_CONTROL_VALUE         1067
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
